// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Prompt.Extra;
using ApiSdk.Prompt.Init;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ApiSdk.Prompt
{
    /// <summary>
    /// Builds and executes requests for operations under \Prompt
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PromptRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Extra property</summary>
        public global::ApiSdk.Prompt.Extra.ExtraRequestBuilder Extra
        {
            get => new global::ApiSdk.Prompt.Extra.ExtraRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Init property</summary>
        public global::ApiSdk.Prompt.Init.InitRequestBuilder Init
        {
            get => new global::ApiSdk.Prompt.Init.InitRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Prompt.PromptRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PromptRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Prompt", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Prompt.PromptRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PromptRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Prompt", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
